# Generated by Django 6.0.2 on 2026-02-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votels',
            new_name='votes',
        ),
    ]
